ECommMVC.UI/Controllers/CartController.cs
using ECommMVC.BL.Abstact;
using ECommMVC.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace ECommMVC.UI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IProductService _productService;
        private IUserService _userService;
        private IOrderService _orderService;
        private IOrderDetailService _orderDetailService;
        private IPaymentService _paymentService;
        private const string CartCookieKey = "cart";

        public CartController(ICartService cartService, IProductService productService, IUserService userService, IOrderService orderService, IOrderDetailService orderDetailService, IPaymentService paymentService)
        {
            _cartService = cartService;
            _productService = productService;
            _userService = userService;
            _orderService = orderService;
            _orderDetailService = orderDetailService;
            _paymentService = paymentService;
        }

        public IActionResult Index()
        {
            var cart = GetCartFromCookies();
            return View(cart);
        }

        public async Task<IActionResult> AddToCart(int id, int quantity)
        {
            var product = await _productService.GetByIdAsync(id);
            var item = new CartItem
            {
                ProductID = id,
                ProductName = product.Name,
                Quantity = quantity,
                Price = product.TotalPrice,
            };

            var cart = GetCartFromCookies();
            cart = _cartService.AddToCart(cart, item);
            SaveCartToCookies(cart);

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            Response.Cookies.Delete(CartCookieKey);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Checkout()
        {
            var claimUserIdStr = User.FindFirst("ID")?.Value;
            if (claimUserIdStr != null)
            {
                int claimUserId = Convert.ToInt32(claimUserIdStr);
                var user = await _userService.GetByIdAsync(claimUserId);
                if (user != null)
                {
                    if (user.Email == User.FindFirst("Email")?.Value && user.FirstName == User.FindFirst("FirstName")?.Value && user.LastName == User.FindFirst("LastName")?.Value)
                    {

                        var cart = GetCartFromCookies();

                        List<Product> products = new List<Product>();
                        foreach (var item in cart)
                        {
                            products.Add(await _productService.GetByIdAsync(item.ProductID));
                        }

                        ViewBag.Cart = cart;
                        ViewBag.Address = $"{user.Address} {user.PostalCode} {user.Region} {user.Region} {user.City}/{user.Country}";
                        ViewBag.Products = products;
                        ViewBag.User = user;

                        ViewBag.PaymentTypes = Enum.GetValues(typeof(PaymentType)).Cast<PaymentType>().Select(e => new SelectListItem
                        {
                            Value = ((int)e).ToString(),
                            Text = e.ToString()
                        }).ToList();
                    }
                    else
                    {
                        Unauthorized();
                    }
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(Checkout checkout)
        {
            if (ModelState.IsValid)
            {
                var claimUserIdStr = User.FindFirst("ID")?.Value;
                if (claimUserIdStr != null)
                {
                    int claimUserId = Convert.ToInt32(claimUserIdStr);
                    var user = await _userService.GetByIdAsync(claimUserId);
                    if (user != null)
                    {
                        if (user.Email == User.FindFirst("Email")?.Value && user.FirstName == User.FindFirst("FirstName")?.Value && user.LastName == User.FindFirst("LastName")?.Value)
                        {

                            var cart = GetCartFromCookies();

                            decimal totalPrice = 0.00m;
                            decimal totalVAT = 0.00m;
                            decimal totalDiscount = 0.00m;
                            decimal totalPaid = 0.00m;

                            List<Product> products = new List<Product>();
                            
                            foreach (var item in cart)
                            {
                                Product product = await _productService.GetByIdAsync(item.ProductID);
                                products.Add(product);

                                totalPrice += (product.UnitPrice * item.Quantity);
                                totalVAT += (product.UnitPrice * product.VAT);
                                totalDiscount += (product.UnitPrice * product.Discount);
                                totalPaid += ((product.UnitPrice * item.Quantity) * (1 + product.VAT) * (1 - product.Discount));
                            }

                            Order order = new Order
                            {
                                Freight = totalPaid,
                                OrderDate = DateTime.Now,
                                ShipAddress = user.Address,
                                ShipCity = user.City,
                                ShipRegion = user.Region,
                                ShipPostalCode = user.PostalCode,
                                ShipCountry = user.Country,
                                User = user
                            };

                            Payment payment = new Payment
                            {
                                PaymentMethod = checkout.PaymentType.ToString(),
                                Freight = totalPaid,
                                User = user
                            };

                            List<OrderDetail> orderDetails = new List<OrderDetail>();
                            foreach (var item in products)
                            {
                                orderDetails.Add(new OrderDetail
                                {
                                    Order = order,
                                    UnitPrice = item.UnitPrice,
                                    Quantity = cart.First(x => x.ProductID == item.ID).Quantity,
                                    Discount = item.Discount,
                                    VAT = item.VAT,
                                    TotalPrice = item.TotalPrice,
                                    Product = item
                                });
                            }

                            //order.Payment = payment;

                            var savedData = await _orderService.CreateOrderWithPaymentAsync(order, payment);

                            if (savedData == null)
                            {
                                throw new Exception("Order and Payment save not completed!");
                            }
                            
                            List<OrderDetail> createdOrderDetails = await _orderDetailService.CreateOrderDetailByListAsync(orderDetails);

                            if ((createdOrderDetails.Count < 0))
                            {
                                throw new Exception("Order not completed!");
                            }

                            return RedirectToAction("OrderCompleted");
                        }
                        else
                        {
                            Unauthorized();
                        }
                    }
                }
            }

            // Hatalıysa tekrar formu göster
            ViewBag.PaymentTypes = Enum.GetValues(typeof(PaymentType)).Cast<PaymentType>().Select(e => new SelectListItem
            {
                Value = ((int)e).ToString(),
                Text = e.ToString()
            }).ToList();

            return RedirectToAction("Checkout");
        }

        public IActionResult OrderCompleted()
        {
            return View();
        }

        private List<CartItem> GetCartFromCookies()
        {
            var cartJson = Request.Cookies[CartCookieKey];
            if (string.IsNullOrEmpty(cartJson))
            {
                return new List<CartItem>();
            }
            return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
        }

        private void SaveCartToCookies(List<CartItem> cart)
        {
            var cartJson = JsonConvert.SerializeObject(cart);
            Response.Cookies.Append(CartCookieKey, cartJson, new CookieOptions
            {
                Expires = System.DateTime.Now.AddDays(7),
                HttpOnly = true
            });
        }
    }
}

ECommMVC.UI/Controllers/ShopController.cs
using ECommMVC.BL.Abstact;
using ECommMVC.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;

namespace ECommMVC.UI.Controllers
{
    [AllowAnonymous]
    public class ShopController : Controller
    {
        private ICategoryService _categoryService;
        private IProductService _productService;
        private IReviewService _reviewService;

        public ShopController(ICategoryService categoryService, IProductService productService, IReviewService reviewService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _reviewService = reviewService;
        }

        // Shopping Page Index
        [HttpGet("shop/category/{id}/{page?}")]
        public async Task<IActionResult> Index(int id, int? page)
        {
            int pageNumber = page ?? 1 ;

            var category = await _categoryService.GetByIdAsync(id);

            if (category != null || id == 0)
            {
                if (id != null)
                {
                    int pageSize = 18;
                    int totalPage = 0;
                    
                    List<Product> products = new List<Product>();

                    if (id > 0)
                    {
                        products = (await _productService.GetAllAsync())
                            .Where(w => w.CategoryID == id)
                            .OrderBy(o => o.ID)
                            .Skip((pageNumber - 1) * pageSize)
                            .Take(pageSize)
                            .ToList();
                    }
                    else if (id == 0)
                    {
                        products = (await _productService.GetAllAsync())
                            .OrderBy(o => o.ID)
                            .Skip((pageNumber - 1) * pageSize)
                            .Take(pageSize)
                            .ToList();    
                    }

                    totalPage = (int)Math.Ceiling((double)products.Count() / pageSize);
                    if (totalPage < 1)
                        totalPage = 1;

                    ViewBag.PageRange = GetPageRange(totalPage, pageNumber);
                    ViewBag.PageNumber = pageNumber;
                    ViewBag.TotalPage = totalPage;
                    ViewBag.Products = products;

                    if (category != null)
                    {
                        ViewData["Title"] = category.Name + " - Page: " + pageNumber;
                    }
                    else
                    {
                        ViewData["Title"] = "All Categories" + " - Page: " + pageNumber;
                    }
                    
                    return View();
                }
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // Product Details
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetByIdWithRefAsync(id);
            var reviews = (await _reviewService.GetAllWithRefAsync()).Where(x => x.ProductID == id && x.IsApproved == true);
            if (product != null)
            {
                ViewBag.Reviews = reviews;
                ViewData["Title"] = product.Name;
                return View(product);
            }
            return RedirectToAction("Index", "Home");
        }

        private List<int> GetPageRange(int totalPage, int pageNumber)
        {
            List<int> pageRange = new List<int>();

            if (totalPage <= 3)
            {
                for (int i = 1; i <= totalPage; i++)
                {
                    pageRange.Add(i);
                }
            }
            else
            {
                int startPage = pageNumber - 1;
                int endPage = pageNumber + 1;

                if (pageNumber <= 2)
                {
                    startPage = 1;
                    endPage = 3;
                }
                else
                {
                    startPage = pageNumber - 1;
                    endPage = pageNumber;
                    if ((pageNumber + 1) <= totalPage)
                    {
                        endPage = pageNumber + 1;
                    }
                    else
                    {
                        startPage--;
                    }
                }

                for (int i = startPage; i < endPage + 1; i++)
                {
                    pageRange.Add(i);
                }
            }

            return pageRange;
        }
    }
}

ECommMVC.UI/Views/Shared/Components/Pagination/PaginationViewComponent.cs
using ECommMVC.BL.Abstact;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ECommMVC.UI.Views.Shared.Components.Pagination
{
    public class PaginationViewComponent : ViewComponent
    {
        public PaginationViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

ECommMVC.UI/Views/Shop/Details.cshtml
@model ECommMVC.Entities.Product

@{
    string category = Model.Category.Name ?? "";
}

<h6>@category > @Model.Name</h6>

<section class="py-1">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/images/product/@(Model.Image ?? "empty.bmp")" alt="" /></div>
            <div class="col-md-6">
                <div class="small mb-1">Product ID: @Model.ID</div>
                <input type="hidden" id="id" name="id" value="@Model.ID" />
                <h1 class="display-5 fw-bolder">@Model.Name</h1>
                <div class="fs-5 mb-5">
                    @if(Model.Discount > 0)
                    {
                        <span class="text-decoration-line-through">@((Model.UnitPrice * (1 + Model.VAT)).ToString("N2"))&#8378</span>
                    }
                    <span>@(Model.TotalPrice.ToString("N2"))&#8378</span>
                </div>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="number" value="1" style="max-width: 5rem" />
                    <a id="addToCart" class="btn btn-outline-dark flex-shrink-0" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.ID" asp-route-quantity="">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                    </a>
                </div>
                <p class="lead">@Html.Raw((Model.Description ?? ""))</p>
            </div>
            
        </div>
    </div>
</section>

<div class="card">
    <div class="card-header">
        Reviews
    </div>
    @if(ViewBag.Reviews != null)
    {
        @foreach (var review in ViewBag.Reviews)
        {
            <div class="card-body">
                <div class="card-title">@((review.User.FirstName ?? "") + " " + (review.User.LastName ?? ""))'s review:</div>
                <div class="card-subtitle">
                    <div class="d-flex small text-warning mb-2">
                        @for (int i = 0; i < 5; i++)
                        {
                            <div class="bi-star@(review.Rating>i ? "-fill" : "")"></div>
                        }
                    </div>
                </div>
                <div class="card-text">@review.Text</div>
            </div>
            <hr class="m-0"/>
        }
    }
    else
    {
        <div class="card-body">
            <div class="card-text">No Review</div>
        </div>
    }
</div>

<script>
    document.getElementById('addToCart').addEventListener('click', function (event) {
        event.preventDefault(); // Sayfanın yeniden yüklenmesini engeller
        var quantity = document.getElementById('inputQuantity').value;
        var id = document.getElementById('id').value;
        // URL'yi oluştur ve yönlendir
        var url = '@Url.Action("AddToCart", "Cart")' + '/' + id + '?quantity=' + quantity;
        window.location.href = url;
    });
</script>

ECommMVC.UI/Views/Shop/Index.cshtml
@{
    //ViewData["Title"] = "";
}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach(var product in ViewBag.Products)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" height="250" src="/images/Product/@(product.Image ?? "empty.bmp")" alt="" />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@product.Name</h5>
                                @if(product.Discount > 0)
                                {
                                    <span class="text-muted text-decoration-line-through">@((product.UnitPrice * (1 + product.VAT)).ToString("N2"))&#8378;</span>
                                }
                                @(product.TotalPrice.ToString("N2"))&#8378;
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@product.ID" asp-route-quantity="1">Add to cart</a>
                                <a class="btn btn-outline-dark mt-auto" asp-action="Details" asp-controller="Shop" asp-route-id="@product.ID">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

@await Component.InvokeAsync("Pagination")